name: Publish Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Cache Dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'

      - name: Build Target Package
        run: npm run build

      - name: Verify NPM Token
        run: |
          if [ -z "${{ secrets.ZEM_ACCESS_TOKEN }}" ]; then
            echo "❌ ERROR: Missing ZEM_ACCESS_TOKEN secret"
            exit 1
          fi

      - name: Publish Extension
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ZEM_ACCESS_TOKEN }}